### ISSUE TITLE
BlazTech is a tyrant

### ISSUE THREAD

**Issue by Anastazbnko** [BlazTech/Hordle#6]
# Feature request

Why do you not accept pull requests that are CLEARLY better than youre code
your just JEALOUS of my CODING ABILITY
YOUR A NOOB YOU SUCK AT PROGRAMING

**Comment by Anastazbnko** [comment]
of corse your going to ignore it all
noob
be ashamed ofn youreself

**Comment by Anastazbnko** [comment]
i beat you at
king of hill chess
king racing chess

you only beat me at
- tree check chess (which is for noobs anyway)
WHY WONT YOU ACCIPIO, 4. MY PULL REQEUST

**Comment by BlazTech** [comment]
Very funny comment
